services:
  reporter-manager:
    container_name: reporter-manager
    restart: always
    build:
      context: ../../
      dockerfile: ./components/manager/Dockerfile
      secrets:
        - github_token
    env_file:
      - .env
    environment:
      - SEAWEEDFS_HOST=${SEAWEEDFS_HOST}
      - SEAWEEDFS_FILER_PORT=${SEAWEEDFS_FILER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/manager
    networks:
      - reporter-infra-network
      - infra-network
      - plugin-fees-network
      - reporter-manager-network
      - plugin-auth-network
      - plugin-crm-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true
  plugin-fees-network:
    driver: bridge
  reporter-manager-network:
    driver: bridge
  plugin-auth-network:
    driver: bridge
  plugin-crm-network:
    driver: bridge

secrets:
  github_token:
    file: ../../.secrets/github_token.txt
