services:
  reporter-manager:
    container_name: reporter-manager
    restart: always
    build:
      context: ../../
      dockerfile: ./components/manager/Dockerfile
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4005/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/manager
    networks:
      - reporter-infra-network
      - infra-network
      - reporter-manager-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true
  reporter-manager-network:
    driver: bridge
