services:
  manager:
    container_name: plugin-template-engine-manager
    restart: always
    build:
      context: ../../
      dockerfile: ./components/manager/Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    networks:
      - template-engine-infra-network
      - template-engine-manager-network
      - infra-network

networks:
  infra-network:
    name: infra-network
    driver: bridge
    external: true
  template-engine-infra-network:
    name: template-engine-infra-network
    driver: bridge
    external: true
  template-engine-manager-network:
    name: template-engine-manager-network
    driver: bridge