services:
  reporter-manager:
    container_name: reporter-manager
    restart: always
    build:
      context: ../../
      dockerfile: ./components/manager/Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/manager
    networks:
      - reporter-infra-network
      - infra-network
      - plugin-fees-network
      - reporter-manager-network
      - plugin-auth-network
      - plugin-crm-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true
  plugin-fees-network:
    external: true
  reporter-manager-network:
    driver: bridge
  plugin-auth-network:
    external: true
  plugin-crm-network:
    external: true

