services:
  plugin-smart-templates-manager:
    container_name: plugin-smart-templates-manager
    restart: always
    build:
      context: ../../
      dockerfile: ./components/manager/Dockerfile
      secrets:
        - github_token
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/manager
    networks:
      - plugin-smart-templates-infra-network
      - infra-network
      - plugin-fees-network
      - plugin-smart-templates-manager-network
      - plugin-auth-network
      - plugin-crm-network

networks:
  plugin-smart-templates-infra-network:
    external: true
  infra-network:
    external: true
  plugin-fees-network:
    driver: bridge
  plugin-smart-templates-manager-network:
    driver: bridge
  plugin-auth-network:
    driver: bridge
  plugin-crm-network:
    name: plugin-crm-network
    driver: bridge

secrets:
  github_token:
    file: ../../.secrets/github_token.txt
