services:
  plugin-template-engine-worker:
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile
    container_name: plugin-template-engine-worker
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/worker
    networks:
      - plugin-template-engine-network
      - infra-network

networks:
  plugin-template-engine-network:
    external: true
  infra-network:
    external: true