services:
  reporter-worker:
    container_name: reporter-worker
    restart: always
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f worker || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - .:/usr/src/worker
    networks:
      - reporter-infra-network
      - infra-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true