name: reporter-test

services:
  reporter-worker-test:
    container_name: reporter-worker-test
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile.test
      secrets:
        - github_token
    env_file:
      - .env.test
    volumes:
      - .:/usr/src/worker
    networks:
      - reporter-test-network

networks:
  reporter-test-network:
    name: reporter-test-network
    driver: bridge
    external: true

secrets:
  github_token:
    file: ../../.secrets/github_token.txt