services:
  plugin-smart-templates-worker:
    container_name: plugin-smart-templates-worker
    restart: always
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile
      secrets:
        - github_token
    env_file:
      - .env
    volumes:
      - .:/usr/src/worker
    networks:
      - plugin-smart-templates-infra-network
      - infra-network
      - plugin-fees-network

networks:
  plugin-smart-templates-infra-network:
    external: true
  infra-network:
    external: true
  plugin-fees-network:
    driver: bridge

secrets:
  github_token:
    file: ../../.secrets/github_token.txt