services:
  reporter-worker:
    container_name: reporter-worker
    restart: always
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/worker
    networks:
      - reporter-infra-network
      - infra-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true