services:
  reporter-worker:
    container_name: reporter-worker
    restart: always
    build:
      context: ../../
      dockerfile: ./components/worker/Dockerfile
      secrets:
        - github_token
    env_file:
      - .env
    volumes:
      - .:/usr/src/worker
    networks:
      - reporter-infra-network
      - infra-network
      - plugin-fees-network
      - plugin-crm-network

networks:
  reporter-infra-network:
    external: true
  infra-network:
    external: true
  plugin-fees-network:
    external: true
  plugin-crm-network:
    external: true

secrets:
  github_token:
    file: ../../.secrets/github_token.txt