name: reporter-test

services:
  reporter-ui-test:
    container_name: reporter-ui-test
    build:
      context: ../..
      dockerfile: components/frontend/Dockerfile.test
    ports:
      - 8083:8083

    env_file:
      - .env.test
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:8083/api/admin/health/ready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reporter-test-network

networks:
  reporter-test-network:
    name: reporter-test-network
    driver: bridge
    external: true
