name: reporter-test

services:
  reporter-mongodb:
    container_name: reporter-mongodb-test
    image: mongo:latest
    env_file:
      - .env
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
    user: root
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: mongod --port ${MONGO_PORT}
    volumes:
      - reporter-mongodb-data-test:/data/db
    networks:
      - reporter-test-network

  reporter-rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: reporter-rabbitmq-test
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT_HOST}:${RABBITMQ_PORT_HOST}
      - ${RABBITMQ_PORT_AMQP}:${RABBITMQ_PORT_AMQP}
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - reporter-test-network

  reporter-seaweedfs-master:
    image: chrislusf/seaweedfs:3.97
    container_name: reporter-seaweedfs-master-test
    ports:
      - "${SEAWEEDFS_MASTER_PORT:-9333}:9333"
      - "${SEAWEEDFS_MASTER_UI_PORT:-9334}:9334"
    command: "master -ip=reporter-seaweedfs-master -port=9333 -mdir=/data"
    volumes:
      - reporter-seaweedfs-master-data-test:/data
    networks:
      - reporter-test-network
    restart: always

  reporter-seaweedfs-volume:
    image: chrislusf/seaweedfs:3.97
    container_name: reporter-seaweedfs-volume-test
    ports:
      - "${SEAWEEDFS_VOLUME_PORT:-9080}:9080"
    command: "volume -ip=reporter-seaweedfs-volume -port=9080 -mserver=reporter-seaweedfs-master-test:9333 -dir=/data -max=0"
    volumes:
      - reporter-seaweedfs-volume-data-test:/data
    networks:
      - reporter-test-network
    depends_on:
      - reporter-seaweedfs-master
    restart: always

  reporter-seaweedfs-filer:
    image: chrislusf/seaweedfs:3.97
    container_name: reporter-seaweedfs-filer-test
    ports:
      - "${SEAWEEDFS_FILER_PORT:-8888}:8888"
      - "${SEAWEEDFS_FILER_S3_PORT:-8333}:8333"
    command: "filer -ip=reporter-seaweedfs-filer -port=8888 -master=reporter-seaweedfs-master-test:9333"
    volumes:
      - reporter-seaweedfs-filer-data-test:/data
    networks:
      - reporter-test-network
    depends_on:
      - reporter-seaweedfs-master
      - reporter-seaweedfs-volume
    restart: always

  reporter-keda:
    image: ghcr.io/kedacore/keda:2.16.0
    container_name: reporter-keda-test
    environment:
      - KEDA_OPERATOR_LOG_LEVEL=info
      - KEDA_OPERATOR_RABBITMQ_HOST=reporter-rabbitmq
      - KEDA_OPERATOR_RABBITMQ_PORT=${RABBITMQ_PORT_AMQP}
      - KEDA_OPERATOR_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - KEDA_OPERATOR_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - KEDA_OPERATOR_RABBITMQ_QUEUE=smart-templates-queue
    ports:
      - "8000:8000"
    depends_on:
      - reporter-rabbitmq
    networks:
      - reporter-test-network

  reporter-valkey:
    container_name: reporter-valkey-test
    image: valkey/valkey:latest
    env_file:
      - .env
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}",  "--port", "${REDIS_PORT}" ]
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - reporter-redis-data-test:/data
    networks:
      - reporter-test-network

volumes:
  reporter-mongodb-data-test:
  reporter-seaweedfs-master-data-test:
  reporter-seaweedfs-volume-data-test:
  reporter-seaweedfs-filer-data-test:
  reporter-redis-data-test:

networks:
  reporter-test-network:
    name: reporter-test-network
    driver: bridge