services:
  plugin-smart-templates-mongodb:
    container_name: plugin-smart-templates-mongodb
    image: mongo:latest
    env_file:
      - .env
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
    user: root
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: mongod --port ${MONGO_PORT}
    volumes:
      - plugin-smart-templates-mongodb-data:/data/db
    networks:
      - plugin-smart-templates-infra-network

  plugin-smart-templates-rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: plugin-smart-templates-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT_HOST}:${RABBITMQ_PORT_HOST}
      - ${RABBITMQ_PORT_AMQP}:${RABBITMQ_PORT_AMQP}
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - plugin-smart-templates-infra-network

  plugin-smart-templates-seaweedfs-master:
    image: chrislusf/seaweedfs:3.97
    container_name: plugin-smart-templates-seaweedfs-master
    ports:
      - "${SEAWEEDFS_MASTER_PORT:-9333}:9333"
      - "${SEAWEEDFS_MASTER_UI_PORT:-9334}:9334"
    command: "master -ip=plugin-smart-templates-seaweedfs-master -port=9333 -mdir=/data"
    volumes:
      - plugin-smart-templates-seaweedfs-master-data:/data
    networks:
      - plugin-smart-templates-infra-network
    restart: always

  plugin-smart-templates-seaweedfs-volume:
    image: chrislusf/seaweedfs:3.97
    container_name: plugin-smart-templates-seaweedfs-volume
    ports:
      - "${SEAWEEDFS_VOLUME_PORT:-9080}:9080"
    command: "volume -ip=plugin-smart-templates-seaweedfs-volume -port=9080 -mserver=plugin-smart-templates-seaweedfs-master:9333 -dir=/data -max=0"
    volumes:
      - plugin-smart-templates-seaweedfs-volume-data:/data
    networks:
      - plugin-smart-templates-infra-network
    depends_on:
      - plugin-smart-templates-seaweedfs-master
    restart: always

  plugin-smart-templates-seaweedfs-filer:
    image: chrislusf/seaweedfs:3.97
    container_name: plugin-smart-templates-seaweedfs-filer
    ports:
      - "${SEAWEEDFS_FILER_PORT:-8888}:8888"
      - "${SEAWEEDFS_FILER_S3_PORT:-8333}:8333"
    command: "filer -ip=plugin-smart-templates-seaweedfs-filer -port=8888 -master=plugin-smart-templates-seaweedfs-master:9333"
    volumes:
      - plugin-smart-templates-seaweedfs-filer-data:/data
    networks:
      - plugin-smart-templates-infra-network
    depends_on:
      - plugin-smart-templates-seaweedfs-master
      - plugin-smart-templates-seaweedfs-volume
    restart: always

  plugin-smart-templates-keda:
    image: ghcr.io/kedacore/keda:2.16.0
    container_name: plugin-smart-templates-keda
    environment:
      - KEDA_OPERATOR_LOG_LEVEL=info
      - KEDA_OPERATOR_RABBITMQ_HOST=plugin-smart-templates-rabbitmq
      - KEDA_OPERATOR_RABBITMQ_PORT=${RABBITMQ_PORT_AMQP}
      - KEDA_OPERATOR_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - KEDA_OPERATOR_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - KEDA_OPERATOR_RABBITMQ_QUEUE=smart-templates-queue
    ports:
      - "8000:8000"
    depends_on:
      - plugin-smart-templates-rabbitmq
    networks:
      - plugin-smart-templates-infra-network

  plugin-smart-templates-valkey:
    container_name: plugin-smart-templates-valkey
    image: valkey/valkey:latest
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}",  "--port", "${REDIS_PORT}" ]
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - plugin-smart-templates-redis-data:/data
    networks:
      - plugin-smart-templates-infra-network

volumes:
  plugin-smart-templates-mongodb-data:
  plugin-smart-templates-seaweedfs-master-data:
  plugin-smart-templates-seaweedfs-volume-data:
  plugin-smart-templates-seaweedfs-filer-data:
  plugin-smart-templates-redis-data:

networks:
  plugin-smart-templates-infra-network:
    name: plugin-smart-templates-infra-network
    driver: bridge